### ISSUE TITLE
Create basic structure to start with

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#1]
## Objective

Add the basic structure for a style guide to work on the foundation of the relaunch.

## Background

The current setup seems to have been extended little by little to a point where it got a bit messy. Anyway it would be wrong to start from scratch as a lot of work has already been done. But as the concept of the relaunch introduces a completly new look and feel for the site we need some place to start.

Therefore the idea is to create all the components that make up the new site alongside the currently existing structure in a style guide while using the same tools: grow and gulp. 

As soon as all new components (or most of them) are finished we are then able to use this style guide as a structural starting point for the new site and carefully move/refactor the content of to this developing structure.

## Tasks

- [x] Establish new `frontend` package alongside the main package
- [x] Create a gulp setup based on ES6 to transpile SCSS to CSS
- [x] Decide on a naming/structural scheme for the components

**Comment by matthiasrohmer** [comment]
Thought of `style` as package name at first but I am favouring `frontend` now as things like manifest.json, Service Worker and so on should probably reside there too.

**Comment by matthiasrohmer** [comment]
Decreased the scope of this issue in favour of #2.

**Comment by matthiasrohmer** [comment]
We decided on a component structure for our styles. The further refinement is done in #3.
