### ISSUE TITLE
Design and dimension TM_Component_Reference

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#10]
## Objective

The *TM_Component_Reference* molecule needs to be designed and dimensioned together with the included atoms.

## Background

This teaser seems to be the most basic teaser while still showing a lot of possible variants. Therefore this teaser should be one of the first we implement and needs to be finished in design.

## Tasks
- [x] Finish design of *TM_Component_Reference*
- [x] Dimension *TM_Component_Reference*
- [x] Hand finished design over to the development

**Comment by LongoOfficial** [comment]
As a base for this content molecule following is defined:
[Typography.pdf](https://github.com/jungvonmatt/amp.dev/files/2257288/Typography.pdf)

**Comment by LongoOfficial** [comment]
[TM_Teaser.pdf](https://github.com/jungvonmatt/amp.dev/files/2257372/TM_Teaser.pdf)

**Comment by keevcodes** [comment]
@LongoOfficial @matthiasrohmer @sebil is this component viewable somewhere?
