### ISSUE TITLE
Make it easier for AMP to filter through and look at batches of progress relating to UX / visual design work

### ISSUE THREAD

**Issue by spacedino** [jungvonmatt/amp.dev#171]
Right now I can filter by labels: department:design and department:concept  - but not all issues have the assets attached. Either come up with another label to signal that there is work to be reviewed or always add work, even if its not final. I need a way to quickly browse through these to check in on status between meetings. 

Right now I'm looking for:
- completed components (on staging)
- wireframes / prototypes with the flushed out interactions we've talked about for searching and filtering
- visual designs for additional pages on the docs site (without the people)

## Background

In case I miss meetings, and to quickly look through a bunch of issues at once, it would be nice to have a way for me to find related issues that need my feedback.

## Tasks
- [ ] add @spacedino as asignee to all UX work 
- [x] add actual visual designs / wireframes / artifacts to department:design and department:concept labels. 
- [ ] staging link if the task is for dev to implement
- [ ] add "needs UX review label"

**Comment by LongoOfficial** [comment]
I put together a .zip file with designs for Home, AMP Overview and Docs.
Thought it would make it easier to give feedback when seeing components in context, rather than looking on single elements.
However, I will successively add screenshots / mockup animations to the tickets as well.

https://cloudnine.jvm.de/index.php/s/AP5NnfaSoYT2JNt

**Comment by spacedino** [comment]
@pbakaus @mattludwig @sebastianbenz @CrystalFaith docs images

![1a guides and tutorials overview _desktop](https://user-images.githubusercontent.com/7339798/46545741-2d455180-c895-11e8-9ce9-bdc919de0047.png)

![1a guides and tutorials overview _mobile](https://user-images.githubusercontent.com/7339798/46545747-346c5f80-c895-11e8-9ec2-4e5d7c186807.png)
![1b guides and tutorials detail _desktop](https://user-images.githubusercontent.com/7339798/46545754-39311380-c895-11e8-89e5-efaa926b6f6b.png)
![2 components overview _desktop](https://user-images.githubusercontent.com/7339798/46545758-3d5d3100-c895-11e8-84f6-5009d4da73ac.png)
![3 examples overview _desktop](https://user-images.githubusercontent.com/7339798/46545769-41894e80-c895-11e8-9ce4-262e2484df11.png)

**Comment by spacedino** [comment]
@matthiasrohmer cc/ @LongoOfficial - can we add a "needs UX review" tag for visual design and wireframes? and then a "needs content review" for doc that need copy review?

**Comment by matthiasrohmer** [comment]
This is the issue we were referring to @CrystalFaith, @sebastianbenz, @pbakaus and @mattludwig. In the [attached ZIP](https://cloudnine.jvm.de/index.php/s/AP5NnfaSoYT2JNt) from @LongoOfficial you'll basically find the current state of design.

We will let you know when we provided them to the individual issues but you might still already have a look to think about.

**Comment by matthiasrohmer** [comment]
> @matthiasrohmer cc/ @LongoOfficial - can we add a "needs UX review" tag for visual design and wireframes? and then a "needs content review" for doc that need copy review?

You've been quicker, @spacedino 😁We'll take care of tagging the issues and add their deliverables of for you to look through them and give feedback on them.

**Comment by pbakaus** [comment]
@LongoOfficial @matthiasrohmer quick feedback on docs (not sure this is the right place..):

- the individual doc page looks fine, but I'm missing the callouts, as well as a mobile mock (I don't actually know how to solve the sidenav/table of contents issue)
- The doc overview page is wasted potential, imho. It's a bunch of cards right now, but it could be so much more: The cards take a ton of space, don't really work well on mobile, and are too uniform for the kind of content we'd ideally like on the overview page. In my opinion, the doc overview page deserves to be the ideal landing page for developers, explaining how to use the docs, and giving you a meaningful quickstart.

A couple things I'd love to see on the docs overview page:

- The content from https://www.ampproject.org/docs/getting_started/quickstart, but organized better:
- Where do I start?
- What are the different ways to learn? (Video, Guides, Tutorials, Samples, ...)
- What's the ideal workflow? (From scratch, CMS, tools..)

Does that make sense? Curious to hear @CrystalFaith's thoughts too.

**Comment by spacedino** [comment]
FYI this issue is NOT for feedback. @matthiasrohmer @LongoOfficial does each page already have an issue? If not I can break them out so you can see how we’ve used github to track visual design feedback in the past. It’s generally easier to keep one master issue per version and then break out separate issues based on feedback, similar to how we’re doing features. What do you this? This issue is for process to make it easier to view ux work so let’s figure that out here.
