### ISSUE TITLE
Cleanup and combine colors and gradients.

### ISSUE THREAD

**Issue by sebil** [jungvonmatt/amp.dev#181]
## Objective
The color/gradient mixins and variables are scattered in multiple files. They need to be combined for a better overview.

## Background
Because of many design changes and co-working on different branches we couldn't define rules for the colors and gradients yet.

## Tasks
- [x] Combine all files where color/gradient mixins are used.
- [x] Rename mixins to meaningful terms.
- [x] Update all components with the changes.
