### ISSUE TITLE
Build a style guide with grow

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#2]
## Objective

There should be a grow setup inside the new `frontend` directory that builds fitting demo pages for the created components.

## Background

Through the work done in #1 we could now start creating our components. As those newly created components can not immediately be used in the existing project we should establish a style guide that we can use to show our current progress.

Instead of using a dedicated templating solution (Nunjucks, Twig or whatever) we should rely on grow to maybe benefit from it in the later process when we begin crafting the real grow views for the live site.

The destination for the `grow build` command should be a new `docs` directory in the project root. This would enable us to show the style guide via GitHub pages then rather than having to setup any dedicated demo environment including tooling.

## Tasks
- [x] Setup a basic grow pod with all needed files
- [x] Configure the setup for `grow run`
- [x] Configure `grow build` to build into `docs`
- [x] Configure Atomic setup

**Comment by keevcodes** [comment]
As discussed, the file structure of grow.io has a few built-ins and while they're not required, some of them are already used in ampproject.org and maybe best to keep them (mainly, content for our front-matter, views and translations folders). Partials is another built-in used for views, however, because we've decided on an Atomic design structure this could be left out in favour of components; this is up for discussion and I will skip this for now.

**Comment by matthiasrohmer** [comment]
Thanks so far @andmckvr13. I'd suggest using the minimum set of features to build the style guide with ease. For the real site we will most probably refactor the existing Grow setup in the project root then.

**Comment by keevcodes** [comment]
I added a new task which is to also implement a basic atomic design structure.

**Comment by keevcodes** [comment]
@matthiasrohmer, would it make sense to have one page containing all of our atoms, molecules, organisms or should we render new pages for each section?

**Comment by matthiasrohmer** [comment]
@andmckvr13, good question actually. I'd say a page per component with each variant of it and then some sort of links page where you are able to jump between components. What do you think?

Maybe you could also have a short chat with Longo what their plans are on presenting finished components, that'd be great.

**Comment by matthiasrohmer** [comment]
@andmckvr13 came up with a nice foundation for the styleguide. I moved the templates over to `frontend/source/j2` and simplified the template/content structure.
