### ISSUE TITLE
Further polish SCSS setup

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#3]
## Objective

Reflect the decision for a atomic structure inside `frontend/source/scss/components` by creating dedicated folders for each type and setting up a dummy component.

## Background

After a face-to-face discussion we are going all-in on atomic design. We commit ourselves to this decision in order to maintain a clean code base.

For the start we want to implement the following types: atoms, molecules, organisms. The plan is to have really precise atoms while offering enough versatility to really only modify them in size in position in the superior types (molecules, organisms). Therefore we also plan to use `rem` whenever possible.

In order to use easily recognize and select our components we want to prefix their selectors with a abbreviation of their category: `a` for atoms, `m` for molecules and so on. To maintain a readable codebase and to be able to maybe omit them later this is done by a SCSS function rather than manually.

## Tasks
- [x] Carefully align the pattern catalogue from the design department with our vision
- [x] Setup a suiting folder structure inside `frontend/source/scss/components`
- [x] Create dummy files for each type including a documentation template (maybe pulled from eis.de)
- [x] Implement SCSS functions to automatically prefix selectors with a project prefix and the element type
