### ISSUE TITLE
Document all the things

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#4]
## Objective

There has already went some thought into our way towards the relaunch. At least the already visible things should be documented.

## Background

We already internally discussed how we want to proceed towards the relaunch. The main idea for now is to work on a style guide based on the new components which could the be used to begin the recontenting work. This should be documented in `frontend/README.md` together with information how to setup this subpackage.

Additonally we should document all the guidelines we would like to stick to during development, like using [gitmoji](https://gitmoji.carloscuesta.me/) for commit messages, using atomic design inside our SCSS, and everything else.

## Tasks
- [ ] Document package setup in `frontend/README.md`
- [ ] `Add frontend/CONTRIBUTING.md` with coding guidelines
- [x] Document each component with the SCSS comment template

**Comment by matthiasrohmer** [comment]
As i haven't been taking care of this for the last two weeks the amount of work this needs naturally increased 😞Definitely needs to be done to get everybody on board.
