### ISSUE TITLE
Design and dimension CM_Copy

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#5]
## Objective

The *CM_Copy* molecule needs to be designed and dimensioned together with the included atoms, to be able to start implementing the corresponding styles in the upcoming sprint.

## Background

As text will be present in most when not all components those need to be the styles we are implementing at first, together with a basic page skeleton including `<amp-font>` therefore they should be ready to implement in the first sprint.

While finalizing the design we need to make sure that we define reasonable variants of sizes to be consistent over all components without the need to make micro adjustments in organisms or templates.

## Tasks
- [x] Finish design of *CM_Copy*
- [x] Dimension *CM_Copy*
- [x] Vend finished design to the development *CM_Copy*

**Comment by LongoOfficial** [comment]
As a base for this molecule follwing is defined:
[Typography.pdf](https://github.com/jungvonmatt/amp.dev/files/2257305/Typography.pdf)

Molecule Layout:
[CM_Copy.pdf](https://github.com/jungvonmatt/amp.dev/files/2257307/CM_Copy.pdf)

**Comment by keevcodes** [comment]
looks great @LongoOfficial
