### ISSUE TITLE
Design and dimension CM_Buttons

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#6]
## Objective

The *CM_Buttons* molecule needs to be designed and dimensioned together with the included atoms.

## Background

Similar to the *CM_Copy* molecule which is handled in issue #5 the *CM_Buttons* molecule is a pattern that will be used across various components in the project and should therefore be implemented fairly early in the project.

What needs to be considered while finalizing the design for the buttons is if for example the icons in front of the links are also represented by the *CM_Button* molecule or if they are part of another component.

## Tasks
- [x] Finish design of *CM_Button*
- [x] Dimension *CM_Button*
- [x] Hand over finalized design to development

**Comment by LongoOfficial** [comment]
[Shadows & Divider.pdf](https://github.com/jungvonmatt/amp.dev/files/2257336/Shadows.Divider.pdf)
[CM_Buttons.pdf](https://github.com/jungvonmatt/amp.dev/files/2257338/CM_Buttons.pdf)

The icons in older designs in front of the links are not related to CM_Buttons anymore. They will be part of CM_Links.

Furthermore we established a new CM_Load_More molecule.

**Comment by keevcodes** [comment]
@LongoOfficial looks good, @sebil has taken care of build this molecule
