### ISSUE TITLE
Design and dimension CM_Links

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#7]
## Objective

The *CM_Links* molecule needs to be designed and dimensioned together with the included atoms.

## Background

Together with the *CM_Copy* molecule (#5) and the *CM_Button* molecule (#6) this one is a low-hanging fruit as it is basically a combination of both.

Tricky thing though might be the handling and dimensioning of the icons.

## Tasks
- [x] Finish design of *CM_Links*
- [x] Dimension *CM_Links*
- [x] Hand finished design over to the development

**Comment by LongoOfficial** [comment]
[CM_Links.pdf](https://github.com/jungvonmatt/amp.dev/files/2257359/CM_Links.pdf)

**Comment by keevcodes** [comment]
@LongoOfficial looks great to us. @sebil is currently implementing this component. closing this issue
