### ISSUE TITLE
Implement the CM_Code_Interactive Molecule

### ISSUE THREAD

**Issue by keevcodes** [jungvonmatt/amp.dev#75]
## Objective

Implement the attached design for the Code Interactive Molecule 

## Background

![screen shot 2018-08-27 at 09 17 37](https://user-images.githubusercontent.com/17259420/44646185-7f639f00-a9da-11e8-825e-3182420d4d85.png)

## Tasks
- [x] Create the component
- [x] Setup demo page
- [x] Accessibility standards to at least AA

**Comment by keevcodes** [comment]
while this component is still missing the code sample, this is another issue that we'll come back to at a later date. Closing the issue for now
