### ISSUE TITLE
Design and dimension CM_Tip

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#8]
## Objective

The *CM_Tip* molecule needs to be designed and dimensioned together with the included atoms.

## Background

#5 lays the foundation for most of the text based components like *CM_Tip*. Therefore it would be nice to finish the design for it to be able to implement it in one of the first sprints.

## Tasks
- [x] Finish design of *CM_Tip*
- [x] Dimension *CM_Tip*
- [x] Hand finished design over to the development

**Comment by LongoOfficial** [comment]
[CM_Tip.pdf](https://github.com/jungvonmatt/amp.dev/files/2257363/CM_Tip.pdf)

The team agreed on defining all additional dimension within the code.

**Comment by keevcodes** [comment]
@LongoOfficial looks good to me.
