### ISSUE TITLE
Refactor and clean current SCSS and corresponding mark-up

### ISSUE THREAD

**Issue by sebil** [jungvonmatt/amp.dev#80]
## Objective

Refactor all the code to be consistent anytime. We should make sure to continue our work on a clean codebase to keep the effort low of changing things in the future.

## Background

The main purpose of refactoring the code is to keep the code base clean. Our goal is to write as little as possible but as much as necessary code. So all unnecessary markup elements like containers, wrappers etc. should be removed from the components. In best case flexbox or css-grid layouts should only be used, when there is no other way. We also should take care about of commenting the SCSS files based on the documentation template we defined earlier. Furthermore we should keep changing styles of typeface, spacing, etc. always up to date and unitize it in all other components.

## Tasks
- [ ] Remove unnecessary html elements from the markup.
- [ ] Reduce SCSS code to a minimum where it's possible.
- [ ] Document SCSS files where comments are missing.
- [ ] Unitize styling classes/modifiers in all components.

**Comment by matthiasrohmer** [comment]
Thanks, @sebil!
