### ISSUE TITLE
Design and dimension CM_Image

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#9]
## Objective

The *CM_Image* molecule needs to be designed and dimensioned.

## Background

To be able to spice up our style guide a bit and not only have rather dull textual wastelands it would be nice to have the design for *CM_Image* finished to be able to implement it in one of the first sprints.

## Tasks
- [x] Finish design of *CM_Image*
- [x] Dimension *CM_Image*
- [x] Hand finished design over to the development

**Comment by LongoOfficial** [comment]
[CM_Image.pdf](https://github.com/jungvonmatt/amp.dev/files/2257365/CM_Image.pdf)

Scroll behavior is not defined in the .PDF yet, but communicated to the team.

**Comment by keevcodes** [comment]
@LongoOfficial looks good!
